name: Swift

on:
  push:
    branches: [ main, "cursor/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app/Contents/Developer"
      - name: Show versions
        run: |
          sw_vers
          xcodebuild -version
          swift --version
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved', 'Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build -c release --disable-sandbox
      - name: Test
        run: |
          set -o pipefail
          swift test -c release --parallel --enable-code-coverage --disable-sandbox 2>&1 | tee test-output.txt
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ github.run_id }}
          path: |
            test-output.txt
            .build/**/codecov*
            .build/**/coverage*
            .build/**/index.json
          if-no-files-found: warn
