name: Swift

on:
  push:
    branches: [ main, "cursor/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Show versions
        run: |
          sw_vers
          xcodebuild -version
          swift --version
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ matrix.configuration }}-${{ hashFiles('**/Package.resolved', 'Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ matrix.configuration }}-
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build -c ${{ matrix.configuration }} --disable-sandbox
      - name: Test
        run: |
          set -o pipefail
          swift test -c ${{ matrix.configuration }} --parallel --enable-code-coverage --disable-sandbox 2>&1 | tee test-output.txt
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ github.run_id }}
          path: |
            test-output.txt
            .build/**/codecov*
            .build/**/coverage*
            .build/**/index.json
          if-no-files-found: warn
