name: Swift

on:
  push:
    branches: [ main, "cursor/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
      - name: Build
        run: swift build -c release
      - name: Test
        run: swift test -c release

